<a href="https://www.kaggle.com/code/paragghatage/regularization?scriptVersionId=258362365" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Regularization

used to prevent overfitting

## Regularized Linear Models

## Ridge regularization
uses l2 norm(Eucledian norm)

In [1]:
import numpy as np

m=1000 # number of instances
X = 6 * np.random.rand(m, 1) - 3
y = 0.5 * X**2 + X + 2 + np.random.randn(m, 1)

with Normal equation

In [2]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=1, solver="cholesky")
ridge_reg.fit(X, y)
ridge_reg.predict([[1.5]])


array([[5.04546879]])

With Gradient descent

In [3]:
from sklearn.linear_model import SGDRegressor

sgd_reg = SGDRegressor(penalty="l2")
sgd_reg.fit(X, y.ravel())
sgd_reg.predict([[1.5]])


array([5.05675112])

## lasso Regression

Lasso does automatically makes some small and less imp parameters to 0.

In [4]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.1)
lasso_reg.fit(X, y)
lasso_reg.predict([[1.5]])

array([4.99676005])

## Elastic Net

its combination of Lasso and Ridge regression.
here mix ratio r (here, l1) decides how much to add ridge cost and lasso cost

$$
J(\theta) = MSE(\theta) + r\alpha \sum_{i=1}^{n} \theta_i 
+ (1-r^2)\alpha \sum_{i=1}^{n} \theta_i^2
$$


if r ==0 --> Ridge regression   
if r == 1 --> Lasso Regression

In [5]:
from sklearn.linear_model import ElasticNet

elaNet = ElasticNet(alpha = 0.1, l1_ratio = 0.5)

elaNet.fit(X,y)

elaNet.predict([[1.5]])

array([4.99672381])