<a href="https://www.kaggle.com/code/paragghatage/regularization?scriptVersionId=258142758" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Regularization

used to prevent overfitting

## Regularized Linear Models

## Ridge regularization
uses l2 norm(Eucledian norm)

In [1]:
import numpy as np

m=1000 # number of instances
X = 6 * np.random.rand(m, 1) - 3
y = 0.5 * X**2 + X + 2 + np.random.randn(m, 1)

with Normal equation

In [2]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=1, solver="cholesky")
ridge_reg.fit(X, y)
ridge_reg.predict([[1.5]])


array([[5.07191818]])

With Gradient descent

In [3]:
from sklearn.linear_model import SGDRegressor

sgd_reg = SGDRegressor(penalty="l2")
sgd_reg.fit(X, y.ravel())
sgd_reg.predict([[1.5]])


array([5.12882974])

## lasso Regression

Lasso does automatically makes some small and less imp parameters to 0.

In [4]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.1)
lasso_reg.fit(X, y)
lasso_reg.predict([[1.5]])

array([5.02714845])