<a href="https://www.kaggle.com/code/paragghatage/support-vector-machines?scriptVersionId=260396538" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

## SVM:
svms try to keep the street maximum as possible and limiting the margin violations.

it fits widest possible street between data,i.e. widest decision boundry

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
iris = datasets.load_iris()
iris = datasets.load_iris()
X = iris["data"][:, (2, 3)] # petal length, petal width
y = (iris["target"] == 2).astype(np.float64) # Iris virginica
svm_clf = Pipeline([
("scaler", StandardScaler()),
("linear_svc", LinearSVC(C=1, loss="hinge")),
])
svm_clf.fit(X, y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('linear_svc', LinearSVC(C=1, loss='hinge'))])

In [2]:
svm_clf.predict([[5.5, 1.7]])

array([1.])

Non Linear SVC- Most datasets are not linear but we can make them linear by adding Polynomial features just like Polynomial regression.

In [3]:
from sklearn.datasets import make_moons
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
X, y = make_moons(n_samples=100, noise=0.15)
polynomial_svm_clf = Pipeline([
("poly_features", PolynomialFeatures(degree=3)),
("scaler", StandardScaler()),
("svm_clf", LinearSVC(C=10, loss="hinge"))
])
polynomial_svm_clf.fit(X, y)

Pipeline(steps=[('poly_features', PolynomialFeatures(degree=3)),
                ('scaler', StandardScaler()),
                ('svm_clf', LinearSVC(C=10, loss='hinge'))])

## Polynomial kernal-
gives same effect as adding polynomial features of large degree without even adding actiual polynomial features.

Mathematical trick to get results same as adding polynomial features of high degree.

In [4]:
from sklearn.svm import SVC
poly_kernel_svm_clf = Pipeline([
("scaler", StandardScaler()),
("svm_clf", SVC(kernel="poly", degree=3, coef0=1, C=5)) #coef0 controls how much the model is influenced by highdegree polynomials versus low-degree polynomials.
])
poly_kernel_svm_clf.fit(X, y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svm_clf', SVC(C=5, coef0=1, kernel='poly'))])

## Similarity Features-
calculates similarity of each instance to the landmark

We get transformed dataset which is linearly seperabel and has excat number of fetures as of original dataset.

### Similarity function( with Gaussian Radial Basis Function)

$\varphi_{\gamma}(x, \ell) = \exp\left(-\gamma \| x - \ell \|^{2}\right)$


In [5]:
rbf_kernel_svm_clf = Pipeline([
("scaler", StandardScaler()),
("svm_clf", SVC(kernel="rbf", gamma=5, C=0.001))
])
rbf_kernel_svm_clf.fit(X, y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svm_clf', SVC(C=0.001, gamma=5))])

# SVM Regression

In [6]:
from sklearn import svm

svr  = svm.SVR(epsilon=0.1)

svr.fit(X,y)
svr.predict(X)

array([ 0.01409668, -0.06199447,  0.71910021,  0.03747825, -0.02252645,
       -0.09045041,  1.05820813,  1.01150195,  1.00843732,  0.19491628,
       -0.04800454, -0.07150572,  1.08580061, -0.09234734,  0.90002722,
        0.04798442,  0.57965445,  1.09550811,  0.93278428,  0.04493423,
        1.01659665,  0.02896405,  1.09990962, -0.06665149,  0.74967726,
       -0.08482835,  0.27498543,  0.08957517,  0.9521936 ,  1.02819716,
        1.02062256,  1.00431986,  1.04404747,  0.97891132,  0.09340516,
        1.10011877,  0.53162821,  0.96080376,  0.1139557 ,  0.04660546,
        0.69697312,  0.17382643,  0.46678838,  1.04533238,  0.6203665 ,
        0.78452721, -0.04147796,  1.10006851, -0.01135784,  0.14380334,
        1.04132407,  0.40509328,  0.90001005, -0.09999002,  0.91776673,
        0.97528257,  0.91174379, -0.05303482,  0.11040346, -0.03265971,
        1.09965379,  1.10934927,  0.15755058,  0.99064491, -0.04117412,
        0.03842338,  0.10009978,  0.09990555, -0.10039025,  0.21

## Using Polynomial Kernel

In [7]:
from sklearn.svm import SVR
svm_poly_reg = SVR(kernel="poly", degree=2, C=100, epsilon=0.1)
svm_poly_reg.fit(X, y)

SVR(C=100, degree=2, kernel='poly')

In [8]:
svm_poly_reg.predict(X)

array([-0.16315338,  0.76295204,  0.97130371,  0.72774777,  0.25985756,
        0.09997142,  1.06350511,  0.75394647,  1.04293557,  0.84280728,
        0.60302601, -0.15282848,  1.14296933,  0.12843676,  0.76466142,
        0.94266706,  0.59222101,  1.11596695,  0.8760542 ,  0.24893802,
        1.03290681, -0.18642319,  0.73622054,  0.26308707,  0.82530578,
        0.63656996,  0.87434239,  0.89093602,  0.92349176,  0.98855272,
        0.82148415,  0.76586295,  0.70193101,  0.77021397,  0.00816091,
        0.71634415,  0.68334334,  0.90016518,  0.48321475,  0.23144027,
        0.66320342,  0.83037715,  0.50291227,  0.71459637,  0.94126551,
        0.79572499,  0.28939511,  1.11751017, -0.04560097,  0.55448888,
        0.8811478 ,  0.91046483,  0.1826346 ,  0.2634627 ,  0.78399764,
        0.69409042,  0.76322708, -0.36597202,  0.32333555,  0.70828271,
        0.79472701,  0.82151304,  0.70262274,  0.81234509, -0.05397756,
       -0.13471222,  0.68827022,  0.09995356,  0.10626009,  0.21